repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ['--line-length=79']

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.0  # Use the latest revision available
    hooks:
      - id: darglint

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1 
    hooks:
      - id: pydocstyle
        args: [--convention=pep257]  
